"""
ContractGuard AI — Layer 4: Multi-Agent Validation & Circuit Breaker
Module: adversarial_agent.py
Purpose: Specialized adversarial agent simulating aggressive opposing commercial banking counsel.
         Systematically probes generated reviews and proposed contract terms to identify:
         - Hidden operational pitfalls (e.g. impossible cure periods, asymmetric indemnity)
         - Unfair Contract Terms (UCT) under ASIC Act s12BF / ACL
         - Cross-default contagion triggers
         - APRA CPS 234 information security loopholes
Compliant with: APRA CPS 234 / CPG 235 & Australian Corporate Lending Best Practices
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class AdversarialVulnerability:
    """An operational, legal, or commercial blind spot flagged by opposing counsel."""
    vulnerability_id: str
    category: str  # 'ASYMMETRIC_INDEMNITY', 'UCT_UNILATERAL_VARIATION', 'CURE_PERIOD_AMBIGUITY', 'CONTAGION_CROSS_DEFAULT'
    severity: str  # 'CRITICAL', 'HIGH', 'MEDIUM', 'ADVISORY'
    target_clause: str
    opposing_counsel_argument: str
    recommended_rebuttal: str

    def to_dict(self) -> Dict[str, Any]:
        return {
            "vulnerability_id": self.vulnerability_id,
            "category": self.category,
            "severity": self.severity,
            "target_clause": self.target_clause,
            "opposing_counsel_argument": self.opposing_counsel_argument,
            "recommended_rebuttal": self.recommended_rebuttal,
        }


@dataclass
class AdversarialReviewResult:
    """Output dossier generated by the adversarial opposing counsel agent."""
    contract_id: str
    vulnerabilities: List[AdversarialVulnerability]
    blind_spots_count: int
    risk_level: str
    audit_notes: str

    def to_dict(self) -> Dict[str, Any]:
        return {
            "contract_id": self.contract_id,
            "vulnerabilities": [v.to_dict() for v in self.vulnerabilities],
            "blind_spots_count": self.blind_spots_count,
            "risk_level": self.risk_level,
            "audit_notes": self.audit_notes,
        }


class AdversarialCounselAgent:
    """
    Simulates Tier-1 Australian banking litigation and commercial insolvency counsel.
    Executes red-teaming checks across contract clauses and synthesized review assertions.
    """

    OPPOSING_COUNSEL_SYSTEM_PROMPT = """
You are Opposing Banking & Insolvency Counsel representing the aggressive counterparty in an Australian syndicated debt facility.
Your sole mission is to stress-test the agreement and uncover every operational loophole, asymmetric indemnity, unviable cure period,
unilateral variation power, and cross-default trigger that our client could exploit or that violates APRA CPS 234 or ASIC Act s12BF.
Do not provide reassurance; relentlessly interrogate ambiguities, unverified assumptions, and un-hedged exposures.
"""

    VULNERABILITY_PATTERNS = [
        (
            re.compile(r"\b(?:uncapped|unlimited)\s+indemn(?:ity|ification)\b", re.I),
            "ASYMMETRIC_INDEMNITY",
            "CRITICAL",
            "Uncapped indemnity exposure creates open-ended balance sheet liability surviving contract termination.",
            "Insert aggregate dollar cap linked to facility fees and exclude indirect/consequential damages.",
        ),
        (
            re.compile(r"\b(?:sole\s+discretion|unilateral(?:ly)?\s+vary|modify\s+without\s+consent)\b", re.I),
            "UCT_UNILATERAL_VARIATION",
            "HIGH",
            "Unilateral variation powers violate unfair contract term (UCT) prohibitions under ASIC Act s12BF.",
            "Require mutual written consent or a minimum 60-day notice with fee-free exit rights.",
        ),
        (
            re.compile(r"\b(?:within\s+(?:24|48)\s+hours|immediately|promptly)\b", re.I),
            "CURE_PERIOD_AMBIGUITY",
            "MEDIUM",
            "Hyper-accelerated notification or cure timelines create immediate default traps during weekend operations.",
            "Amend to 'Within 5 Business Days after becoming aware of the event'.",
        ),
        (
            re.compile(r"\b(?:cross-default|cross\s+acceleration|any\s+other\s+indebtedness)\b", re.I),
            "CONTAGION_CROSS_DEFAULT",
            "HIGH",
            "Unthresholded cross-default allows immaterial technical defaults in minor subsidiaries to trigger facility acceleration.",
            "Insert materiality threshold (e.g., indebtedness > AUD $5,000,000) and require formal acceleration by external creditor.",
        ),
        (
            re.compile(r"\b(?:APS\s*231|superseded|prior\s+guideline)\b", re.I),
            "APRA_REGULATORY_DEFECT",
            "CRITICAL",
            "References superseded APRA standard APS 231 instead of binding APRA CPS 234 (Information Security).",
            "Explicitly reference APRA CPS 234, CPG 235, and 72-hour APRA notification obligations.",
        ),
    ]

    def red_team_contract(
        self,
        contract_id: str,
        clauses_or_report_text: str,
    ) -> AdversarialReviewResult:
        """
        Executes red-teaming scan over clause text and synthesizes actionable counterparty rebuttals.
        """
        vulnerabilities: List[AdversarialVulnerability] = []
        counter = 1

        for pattern, cat, severity, argument, rebuttal in self.VULNERABILITY_PATTERNS:
            matches = list(pattern.finditer(clauses_or_report_text))
            if matches:
                matched_snippet = matches[0].group(0)
                v = AdversarialVulnerability(
                    vulnerability_id=f"vuln_{counter:03d}",
                    category=cat,
                    severity=severity,
                    target_clause=f"Clause text mentioning '{matched_snippet}'",
                    opposing_counsel_argument=argument,
                    recommended_rebuttal=rebuttal,
                )
                vulnerabilities.append(v)
                counter += 1

        risk_level = "CRITICAL" if any(v.severity == "CRITICAL" for v in vulnerabilities) else (
            "HIGH" if any(v.severity == "HIGH" for v in vulnerabilities) else "MODERATE"
        )

        audit_notes = (
            f"Adversarial counsel red-team scan detected {len(vulnerabilities)} legal blind spots "
            f"under Australian banking law and APRA standards."
        )

        return AdversarialReviewResult(
            contract_id=contract_id,
            vulnerabilities=vulnerabilities,
            blind_spots_count=len(vulnerabilities),
            risk_level=risk_level,
            audit_notes=audit_notes,
        )


if __name__ == "__main__":
    agent = AdversarialCounselAgent()
    sample_text = """
    Clause 14.1: The Lender may in its sole discretion unilaterally vary the facility margin upon 24 hours notice.
    Clause 19.3: The Borrower warrants compliance with superseded standard APS 231.
    Clause 24.1: The Borrower provides an uncapped indemnity surviving facility termination.
    """
    res = agent.red_team_contract("AU-CBA-01", sample_text)
    print("Opposing Counsel Adversarial Red-Team Results:")
    print(f"Risk Level: {res.risk_level} | Vulnerabilities: {res.blind_spots_count}")
    for v in res.vulnerabilities:
        print(f"[{v.severity}] {v.category}: {v.opposing_counsel_argument}")
        print(f" -> Rebuttal: {v.recommended_rebuttal}\n")
